# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependency Updates"
    ignore:
      # For Eslint, ignore all Dependabot updates for version 9 until supported by peer dependencies (typescript-eslint)
      - dependency-name: "eslint"
        versions: ["9.x"]
    groups:
      # group dev dependencies together in a single pull request
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "@eslint*"
          - "@swc*"
          - "@types*"
          - "eslint*"
          - "jest"
          - "nodemon"
          - "prettier"
          - "ts-*"
          - "tsx"
          - "typescript*"
      dev-dependencies-security-updates:
        applies-to: security-updates
        patterns:
          - "@eslint*"
          - "@swc*"
          - "@types*"
          - "eslint*"
          - "jest"
          - "nodemon"
          - "prettier"
          - "ts-*"
          - "tsx"
          - "typescript*"
      # group gRPC packages
      grpc-package-updates:
        applies-to: version-updates
        patterns:
          - "@grpc*"
      grpc-security-updates:
        applies-to: security-updates
        patterns:
          - "@grpc*"
      # group utility updates
      utils-package-updates:
        applies-to: version-updates
        patterns:
          - "@genkit*"
          - "dotenv"
          - "winston"
          - "zod"
          - "kafkajs"
      utils-security-updates:
        applies-to: security-updates
        patterns:
          - "@genkit*"
          - "dotenv"
          - "winston"
          - "zod"
          - "kafkajs"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions Updates"
