apiVersion: v1
kind: Service
metadata:
  name: transac-ai-igs-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: transac-ai-igs
  ports:
  - name: tcp-grpc-port
    protocol: TCP
    port: 80
    targetPort: 8080
